default:
  golem_name: VisualizacaoDados
  golem_version: 0.0.0.9000
  app_prod: no
  con: !expr DBI::dbConnect(RSQLite::SQLite(), "C:/Users/VitorCapdeville/OneDrive/Documentos/GitHub/VisualizacaoDados/inst/app/sinistralidade-sicoob.sqlite")
  colunasFiltro: !expr c("Idade", "NomeProduto", "Cobertura", "TipoProduto", "RamoCodigo")
  colunasFiltroNome: !expr c("Idade", "Produto", "Cobertura", "Tipo de produto", "Ramo c\u00F3digo")
  colunasFiltroTipo: !expr c("slider", "picker", "picker", "picker", "picker")
  colunasTabela: !expr c("NomeProduto", "Cobertura")
  colunasTabelaNome: !expr c("Produto", "Cobertura")
  tabela1: "premioVI"
  tabela2: "sinistroVI"
  colunasValorTabela1: !expr c("PremioEmitido", "PremioGanhoCorrigido", "ComissaoGanha")
  formatosValorTabela1: !expr c("number", "number", "number")
  colunasValorTabela2: !expr c("SinistroComER")
  formatosValorTabela2: !expr c("number")
production:
  app_prod: yes
dev:
  golem_wd: !expr here::here()
