default:
  golem_name: VisualizacaoDados
  golem_version: 0.0.0.9000
  app_prod: no
  con: !expr DBI::dbConnect(RSQLite::SQLite(), "inst/penguins.sqlite")
  colunasFiltro: !expr c("species", "island", "sex", "year","idade", "Flag")
  colunasFiltroNome: !expr c("Species", "Island", "Sex", "Year", "Idade", "Flag")
  colunasFiltroTipo: !expr c("picker", "picker", "picker", "dateRange", "slider", "checkBox")
  colunasTabela: !expr c("Id","species", "island", "sex", "year")
  colunasTabelaNome: !expr c("Long table","Species", "Island", "Sex", "Year")
  tabela1: "bill"
  tabela2: "rest"
  colunasValorTabela1: !expr c("bill_length_mm", "bill_depth_mm")
  colunasValorNomeTabela1: !expr c("Bill length", "Bill depth")
  formatosValorTabela1: !expr c("number", "number")
  colunasValorTabela2: !expr c("flipper_length_mm", "body_mass_g")
  colunasValorNomeTabela2: !expr c("Flipper length", "Body mass")
  formatosValorTabela2: !expr c("number", "number")
  nome_pagina: "Example APP"
  title_header: "APP"
production:
  app_prod: yes
dev:
  golem_wd: !expr here::here()
